### ISSUE TITLE
Misguiding name of test method

### ISSUE THREAD

**Issue by ziemiowid** [bleis-tift/FsYaml#15]
In file FsYaml/FsYaml.Tests/YamlScenario.fs at line 53 method name
  
  ``[ 10 ,2,3 ]というYAML文字列を[1; 2; 3]に変換できる``
should be
 ``[ 10 ,2,3 ]というYAML文字列を[10; 2; 3]に変換できる``

**Comment by hafuu** [comment]
fsyaml2ブランチでテストと実装を書き直しました
