### ISSUE TITLE
Could not find a part of the path 'D:\git-repos\FsYaml\FsYaml\Resources.resx'.

### ISSUE THREAD

**Issue by archaeron** [bleis-tift/FsYaml#27]
The path to the `Resources.resx` seems to be hardcoded.

This happens when I try the short example from: http://bleis-tift.github.io/FsYaml/

**Comment by bleis-tift** [comment]
@archaeron thank you for your report.
This bug comes from [ResXProvider](https://github.com/fsprojects/FSharp.Configuration/blob/master/src/FSharp.Configuration/ResXProvider.fs).

**Comment by archaeron** [comment]
Hey

sorry for the delay.
I just tested this and it's working. Thanks a lot!
