### ISSUE TITLE
Proposal: a new way of loading yaml that gives you back the error if one happens

### ISSUE THREAD

**Issue by archaeron** [bleis-tift/FsYaml#31]
I propose adding a new function:

```f#
let eitherLoad<'a> yamlStr = 
    try 
        Choice2Of2(Yaml.load<'a> yamlStr)
    with e -> Choice1Of2 e
```

this way it's possible to see what goes wrong when parsing your YAML

**Comment by bleis-tift** [comment]
Thanks for your proposal but we do not intend to add such a function yet.
The Choice type represents equivalent options but the success case is more important than the failure case.
There is a [discussion to introduce the Result type to F#](https://github.com/fsharp/FSharpLangDesign/issues/49) and it can be used to resolve this case.
We will add it when the Result type become available.

**Comment by archaeron** [comment]
@bleis-tift fair enough, thanks
